module-template: ! 'module MODULE_NAME where

'
extensions:
  GeneralizedNewtypeDeriving: true
  FunctionalDependencies: true
  FlexibleInstances: true
  MultiParamTypeClasses: true
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
modules:
  TEST:
    filename: src/TEST.hs
  Data.SequenceNumber:
    filename: src/Data/SequenceNumber.hs
version: 1
extra-packages: ''
ghc-args: []
